# Use Node.js LTS version as the base image
FROM node:lts-alpine

# Set the working directory for the backend in the container
WORKDIR /app/src/Backend

# Copy only the backend package.json and lock file initially
COPY src/Backend/package.json .
COPY src/Backend/package-lock.json .

# Copy backend-specific .env file (if needed)
COPY src/Backend/.env .

# Expose the port on which the backend server will run
EXPOSE 8000

# Command to start the backend server
CMD ["npm",  "start"]